name: 🚀 Release
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - id: build
        uses: hoverkraft-tech/ci-github-publish/actions/deploy/jekyll@ed354ada70b9f518c2bb663e18a80041c2cf5156 # 0.27.1
        with:
          pages: |
            README.md
            CODE_OF_CONDUCT.md
            branding/README.md
          assets: |
            branding/*.png
          site-path: website

      - id: deploy
        uses: hoverkraft-tech/ci-github-publish/actions/deploy/github-pages@ed354ada70b9f518c2bb663e18a80041c2cf5156 # 0.27.1
        with:
          build-path: ${{ steps.build.outputs.build-path }}
